bitbag_sylius_product_bundle_admin:
    resource: '@BitBagSyliusProductBundlePlugin/Resources/config/routing/admin.yml'
    prefix: /admin

bitbag_sylius_product_bundle_shop:
    resource: '@BitBagSyliusProductBundlePlugin/Resources/config/routing/shop.yml'
    prefix: /{_locale}
